// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: backlink.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BacklinkExtractorClient is the client API for BacklinkExtractor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BacklinkExtractorClient interface {
	GetBacklinks(ctx context.Context, in *BacklinksRequest, opts ...grpc.CallOption) (*BacklinksResponse, error)
}

type backlinkExtractorClient struct {
	cc grpc.ClientConnInterface
}

func NewBacklinkExtractorClient(cc grpc.ClientConnInterface) BacklinkExtractorClient {
	return &backlinkExtractorClient{cc}
}

func (c *backlinkExtractorClient) GetBacklinks(ctx context.Context, in *BacklinksRequest, opts ...grpc.CallOption) (*BacklinksResponse, error) {
	out := new(BacklinksResponse)
	err := c.cc.Invoke(ctx, "/krang.BacklinkExtractor/GetBacklinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BacklinkExtractorServer is the server API for BacklinkExtractor service.
// All implementations must embed UnimplementedBacklinkExtractorServer
// for forward compatibility
type BacklinkExtractorServer interface {
	GetBacklinks(context.Context, *BacklinksRequest) (*BacklinksResponse, error)
	mustEmbedUnimplementedBacklinkExtractorServer()
}

// UnimplementedBacklinkExtractorServer must be embedded to have forward compatible implementations.
type UnimplementedBacklinkExtractorServer struct {
}

func (UnimplementedBacklinkExtractorServer) GetBacklinks(context.Context, *BacklinksRequest) (*BacklinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBacklinks not implemented")
}
func (UnimplementedBacklinkExtractorServer) mustEmbedUnimplementedBacklinkExtractorServer() {}

// UnsafeBacklinkExtractorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BacklinkExtractorServer will
// result in compilation errors.
type UnsafeBacklinkExtractorServer interface {
	mustEmbedUnimplementedBacklinkExtractorServer()
}

func RegisterBacklinkExtractorServer(s grpc.ServiceRegistrar, srv BacklinkExtractorServer) {
	s.RegisterService(&BacklinkExtractor_ServiceDesc, srv)
}

func _BacklinkExtractor_GetBacklinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BacklinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacklinkExtractorServer).GetBacklinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/krang.BacklinkExtractor/GetBacklinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacklinkExtractorServer).GetBacklinks(ctx, req.(*BacklinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BacklinkExtractor_ServiceDesc is the grpc.ServiceDesc for BacklinkExtractor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BacklinkExtractor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "krang.BacklinkExtractor",
	HandlerType: (*BacklinkExtractorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBacklinks",
			Handler:    _BacklinkExtractor_GetBacklinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backlink.proto",
}
