// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WorkerServerClient is the client API for WorkerServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerServerClient interface {
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CompletePage(ctx context.Context, in *Page, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type workerServerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServerClient(cc grpc.ClientConnInterface) WorkerServerClient {
	return &workerServerClient{cc}
}

func (c *workerServerClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/krang.WorkerServer/Dispatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServerClient) CompletePage(ctx context.Context, in *Page, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/krang.WorkerServer/CompletePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServerServer is the server API for WorkerServer service.
// All implementations must embed UnimplementedWorkerServerServer
// for forward compatibility
type WorkerServerServer interface {
	Dispatch(context.Context, *DispatchRequest) (*emptypb.Empty, error)
	CompletePage(context.Context, *Page) (*emptypb.Empty, error)
	mustEmbedUnimplementedWorkerServerServer()
}

// UnimplementedWorkerServerServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerServerServer struct {
}

func (UnimplementedWorkerServerServer) Dispatch(context.Context, *DispatchRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedWorkerServerServer) CompletePage(context.Context, *Page) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompletePage not implemented")
}
func (UnimplementedWorkerServerServer) mustEmbedUnimplementedWorkerServerServer() {}

// UnsafeWorkerServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServerServer will
// result in compilation errors.
type UnsafeWorkerServerServer interface {
	mustEmbedUnimplementedWorkerServerServer()
}

func RegisterWorkerServerServer(s grpc.ServiceRegistrar, srv WorkerServerServer) {
	s.RegisterService(&WorkerServer_ServiceDesc, srv)
}

func _WorkerServer_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServerServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/krang.WorkerServer/Dispatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServerServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerServer_CompletePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServerServer).CompletePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/krang.WorkerServer/CompletePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServerServer).CompletePage(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerServer_ServiceDesc is the grpc.ServiceDesc for WorkerServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "krang.WorkerServer",
	HandlerType: (*WorkerServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _WorkerServer_Dispatch_Handler,
		},
		{
			MethodName: "CompletePage",
			Handler:    _WorkerServer_CompletePage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
